### ISSUE TITLE
Question about Contributing

### ISSUE THREAD

**Issue by frankgreco** [apigee-internal/microgateway#100]
I have done some really cool stuff deploying the Microgateway as a sidecar container in a Kubernetes pod along with a cool way to do dynamic configurations. I think it would provide value to contribute documentation around this as I image there are many other people looking to use the MG with Kubernetes. 

Would you see value in a contribution like this and if so how should I go about it.

**Comment by mdobson** [comment]
@frankgreco Yeah. That would be interesting. We don't really store that kind of content in github. The apigee community would be a great place for it though. You can create an article that outlines all the information above.

https://community.apigee.com/spaces/71/edge-micro.html

Thanks!

-Matt
