### ISSUE TITLE
no support for wildcard in vhost

### ISSUE THREAD

**Issue by kidiyoor** [apigee-internal/microgateway#119]
Something like below cannot be done
```
vhosts:
  myvhost:
    vhost: "*"
```

Currently just the string match of **Host** is happening. Hence above vhost config will require something like bellow to succeed 

`curl -H 'Host: *' https://microservicedns.com/edge/api`

Ideally I should be able to do as follow

`curl https://microservicedns.com/edge/api`

**Comment by mdobson** [comment]
Makes sense. I think that should be a valid configuration. 

@srinandan Any thoughts on `*` as a vhost config?

**Comment by mukundha** [comment]
I think we need to support wild cards, edge supports it today

**Comment by mukundha** [comment]
@srinandan thoughts? wildcards will be really useful, especially with the hybrid early access.

**Comment by srinandan** [comment]
Supported now. This can be closed.
