### ISSUE TITLE
Wrong config parameter name in EMG doc

### ISSUE THREAD

**Issue by dod38fr** [apigee-internal/microgateway#128]
Hi

Variable `disable_config_poll_interval` (used [there](https://github.com/apigee-internal/microgateway/blob/master/cli/lib/gateway.js#L123) ) is documented as `disabled_config_poll_interval` (with an extra 'd' after disable) [there](http://docs.apigee.com/microgateway/latest/operation-and-configuration-reference-edge-microgateway#edgemicrogatewayconfigurationreference-edgemicroattributes).

Can you fix this discrepancy ?

All the best

**Comment by srinandan** [comment]
I have opened a document defect. it will be fixed soon.

**Comment by WWitman** [comment]
The doc has been corrected. Thanks for letting us know.
