### ISSUE TITLE
edgemicro reload does not support the configuration file option -c

### ISSUE THREAD

**Issue by dmryn** [apigee-internal/microgateway#141]
While attempting to perform a reload of the edgemicro gateway we were unable to specify the configuration file directory and always defaulted to the home directory in which the file did not exist.  I'm thinking the reload command should also support the configuration location flag of -c as well since this doesn't work when using a configuration file stored outside of the users home directory.

We are currently running this version:
node_modules/edgemicro/cli/edgemicro --version
current nodejs version is v8.3.0
current edgemicro version is 2.5.4
2.5.4

**Comment by srinandan** [comment]
I have pushed the code to master. Will be in the next release.

**Comment by srinandan** [comment]
Fixed in v2.5.7
