### ISSUE TITLE
Random "Invalid Token" returned when running on my local microgateway.

### ISSUE THREAD

**Issue by mrobida** [apigee-internal/microgateway#146]
I’m running into an issue with random “invalid token” when testing my local instance of the microgateway.

Running the following command over and over on my instance of microgateway returns a “401 Invalid Token” error randomly:

`  curl -i http://<myipaddress>:8000/v1/demo/docusign/ -H "x-api-key: jy4nTLfezVoG4d5Da7OCOYgUYL24aoag" `

The errors happen randomly, but quite often.  When we try running the same command using a different microgateway server (Dave Ryan’s machine) it works every time, but for some reason when run on my machine I see these errors.  It happens when running curl from the terminal window or when running it from Postman.  I’m running microgateway v2.57 on nodejs v8.6.0

**Here is the output that is returned when it fails:**

 gateway:main selected proxy https://demo.docusign.net/restapi/v2 with base path /v1/demo/docusign for request path /v1/demo/docusign/ +50s
  gateway:main sourceRequest +0ms f7c82f00-a932-11e7-a65a-c54964e7f062 GET /v1/demo/docusign/
  plugin:oauth invalid token +50s
  plugin:oauth auth failure 401 invalid_token  { 'cache-control': 'no-cache',
  'postman-token': 'acee92f7-c2c7-49dd-ba42-0068ca2914e1',
  'x-api-key': 'jy4nTLfezVoG4d5Da7OCOYgUYL24aoag',
  'user-agent': 'PostmanRuntime/6.3.2',
  accept: '*/*',
  host: '10.103.91.95:8000',
  'accept-encoding': 'gzip, deflate',
  connection: 'keep-alive',
  client_received_start_timestamp: 1507142202864 } GET /v1/demo/docusign/ +0ms
  gateway:errors invalid_token +117ms
  analytics flushing 1 records. 0 records remaining. +35ms

**Here is the output that it returns when it succeeds:**

  gateway:main selected proxy https://demo.docusign.net/restapi/v2 with base path /v1/demo/docusign for request path /v1/demo/docusign/ +1m
  gateway:main sourceRequest +0ms 06228000-a933-11e7-81fa-6751874d9626 GET /v1/demo/docusign/
  plugin:oauth product only: false +1m
  plugin:oauth matches proxy rules: /v1/demo/docusign/ +0ms
  plugin:oauth matches proxy rules: /v1/demo/docusign/ +0ms
  plugin:oauth api key cache skip jy4nTLfezVoG4d5Da7OCOYgUYL24aoag +0ms
  gateway:main targetRequest +146ms 06228000-a933-11e7-81fa-6751874d9626 GET demo.docusign.net NaN /restapi/v2/
  gateway:main plugin oauth does not provide handler function for end_request +1ms
  gateway:main targetResponse +377ms 06228000-a933-11e7-81fa-6751874d9626 200
  gateway:main plugin oauth does not provide handler function for response +0ms
  gateway:main [ null, null ] +0ms
  gateway:main req data +0ms 474
  gateway:main plugin oauth does not provide handler function for data_response +0ms
  gateway:main plugin analytics does not provide handler function for data_response +1ms
  gateway:main plugin oauth does not provide handler function for end_response +0ms
  analytics flushing 1 records. 0 records remaining. +515ms

**Comment by srinandan** [comment]
​My best guess at this point is there is a time sync issue between your laptop and the Apigee Server. Let me explain:
When you send an API Key to MG, a sideway call is made to the Apigee Edge org (that is running the edgemicro-auth proxy). The call returns (if the key is valid) a JWT with claims on what APIs/Products the API Key can access. 

In your case, I think the JWT from Apigee (nbf or iat) is out of sync with your machine's time and therefore MG is rejecting the token. 

Here is an option, In the config.yaml file, add the following;
```
oauth:
  allowNoAuthorization: true
  allowInvalidAuthorization: true
  gracePeriod: 10
  verify_api_key_url: 'https://amer-demo13-test.apigee.net/edgemicro-auth/verifyApiKey'
```
this should give you a 10 second gracePeriod.

**Comment by mrobida** [comment]
Interesting!  We've been struggling with getting another microgateway running correctly on someone else's laptop (Steve B.).  In his case he was hitting the Invalid Token error on "every" call.  He just set the gracePeriod to 10 and it resolved his issue.  In my case, I haven't seen the issue occur at all today, but I will keep monitoring it and if I see it start to happen again I'll set the parameter. As we start to utilize microgateway more on various servers I expect we'll see this more often.   Is there a general recommendation for setting this vs. just setting it when we see the problem happen?

**Comment by srinandan** [comment]
That is kinda hard to say. I have never needed this setting. It is possible that on your laptops, NTP is not enabled. When you roll this out to production, I'm guessing your Linux servers will have it enabled. 

I saw Steve's question on Apigee community. My response here was exactly what I told him. I'm glad you have it working.

**Comment by srinandan** [comment]
https://community.apigee.com/questions/47846/microgateway-not-working-with-oauth.html
