### ISSUE TITLE
Microgateway calls edgemicro-auth proxy every time an API call is made with API key

### ISSUE THREAD

**Issue by sudheesreedhara** [apigee-internal/microgateway#148]
Every time I call my edgemicro_* proxy with an API key, Edge Microgateway calls (POST request) the edgemicro-auth proxy to verify the API key. This request returns a JWT token, that's not used to validate subsequent API calls. We could use the JWT to verify the API key for future calls till expiry.

**Comment by srinandan** [comment]
https://community.apigee.com/questions/49267/edge-microgateway-oauth-plugin.html
