### ISSUE TITLE
Incorrect CLI error if using Node JS version 10

### ISSUE THREAD

**Issue by seantdg** [apigee-internal/microgateway#162]
10.1.0 is the latest version of Node at the of writing. Edge Micro CLI reports the error:

"You are using an older version of NodeJS version v10.1.0, please update nodejs to 4.8.4+". This is because a string comparison is used.

https://github.com/apigee-internal/microgateway/blob/master/cli/edgemicro#L28

"v4.8.4" < "v10.1" = false

**Comment by srinandan** [comment]
That code was added for MG to only work with LTS releases. At the moment, v10.x was not a LTS release (https://github.com/nodejs/Release).

**Comment by srinandan** [comment]
Fixed in 2.5.19
