### ISSUE TITLE
PROD Release 2.5.25 references BETA modules

### ISSUE THREAD

**Issue by eschult2001** [apigee-internal/microgateway#189]
A bit of a nitpick here, which may be innocuous, but microgateway 2.5.25 is presented as a PROD release but references BETA dependencies.
If the beta modules are indeed production ready, they should be released as well, no?

**Comment by srinandan** [comment]
You're right. Thanks for bringing this to my attention. I'll fix this in the next release. Regardless on the beta flag, they're supported in production.

**Comment by srinandan** [comment]
2.5.26 is released. there should be no reference to Beta modules.
