### ISSUE TITLE
edgemicro configure error

### ISSUE THREAD

**Issue by smitchell62** [apigee-internal/microgateway#191]
Getting an error when on a fresh edgemicro configure -o ORG  -e ENV USERNAME.

urrent nodejs version is v8.12.0
current edgemicro version is 2.5.26
password:
file doesn't exist, setting up
checking org for existing KVM
error checking for cert. Installing new cert.
creating KVM
adding private_key
adding public_key

/usr/lib/node_modules/edgemicro/cli/lib/cert-lib.js:188
                'value': key.publicKey
                             ^

TypeError: Cannot read property 'publicKey' of undefined
    at /usr/lib/node_modules/edgemicro/cli/lib/cert-lib.js:188:30
    at /usr/lib/node_modules/edgemicro/node_modules/async/lib/async.js:718:13
    at Immediate.iterate [as _onImmediate] (/usr/lib/node_modules/edgemicro/node_modules/async/lib/async.js:262:13)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

Modified the file (cert-lib) to output the error and get the following error:

KEY: Error: Invalid openssl exit code: 1
% openssl x509 -utf8 -in /tmp/f2dc7fc9ea6170dd51804444455c5126c5c0c29a -pubkey -noout
x509: Unknown digest utf8
x509: Use -help for summary.

Running this on a GCE Debian GNU/Linux 9 (stretch) vm.

OpenSSL Version: OpenSSL 1.1.0f  25 May 2017

**Comment by srinandan** [comment]
Hey @smitchell62 

This problem was observed by other on this [thread](https://community.apigee.com/questions/61081/microgateway-configuration-errors-on-windows-10.html).

At the moment, we are suspecting the OpenSSL version you have installed is not backward compatible. FWIW, I have installed this version: OpenSSL 1.0.2p  14 Aug 2018
