### ISSUE TITLE
Installation Steps not working when dowloading content on Linux system

### ISSUE THREAD

**Issue by chrislangston** [apigee-internal/microgateway#192]
Following "Installation Steps" for step 1 to pull down files onto a Linux system as found here:

https://github.com/apigee-internal/microgateway/tree/master/kubernetes

I'm using Ubuntu Server 16.04.5.   Connected into my linux system via ssh shell.

couser@cliot01:~/apigee-kubernetes$ sudo curl -L https://raw.githubusercontent.com/apigee-internal/microgateway/master/kubernetes/release/downloadEdgeMicrok8s.sh | sh -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1494  100  1494    0     0   4379      0 --:--:-- --:--:-- --:--:--  4381
sh: 24: [[: not found
Downloading microgateway__Linux_x86_64 from https://github.com/apigee-internal/microgateway/releases/download//microgateway__Linux_x86_64.tar.gz ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9    0     9    0     0     27      0 --:--:-- --:--:-- --:--:--    27

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Downloaded into microgateway__Linux_x86_64:
sh: 52: cd: can't cd to bin
Add /home/couser/apigee-kubernetes to your path; e.g copy paste in your shell and/or ~/.profile:
export PATH="$PATH:/home/couser/apigee-kubernetes"

What's the correct way to pull the bits down?

Thanks,

Chris

**Comment by srinandan** [comment]
Can you please try to download the zip from here?
https://github.com/apigee-internal/microgateway/releases

**Comment by chrislangston** [comment]
Thanks @srinandan for the reply.
