### ISSUE TITLE
Can't run docker image when customizing the entrypoint.sh file

### ISSUE THREAD

**Issue by chrislangston** [apigee-internal/microgateway#194]
I've forked the repo from here (https://github.com/apigee-internal/microgateway/tree/master/kubernetes/docker/edgemicro) and make some small customization to my Dockerfile and the entrypoint.sh

**Here's the contents of my Dockerfile:**

FROM gcr.io/apigee-microgateway/edgemicro:2.5.25

RUN apt-get install -y nano

WORKDIR /tmp

COPY entrypoint.sh /tmp/entrypoint.sh
COPY setconfig.sh /tmp/setconfig.sh

RUN chmod +x /tmp/setconfig.sh
RUN chmod +x /tmp/entrypoint.sh

WORKDIR /opt/apigee/.edgemicro/
COPY clangston-eval-test-config.yaml /opt/apigee/.edgemicro/clangston-eval-test-config.yaml
RUN chown apigee:apigee /opt/apigee/.edgemicro/*

WORKDIR /tmp

EXPOSE 8000
EXPOSE 8443

ENTRYPOINT ["/tmp/entrypoint.sh"]

When I attempt to run using the following docker run instructions I receive the following error:

All I did inside the entrypoint.sh is to writeout param values for debugging purposes such as
echo ho "Starting apigee with commandString : [ $commandString ]"

**The is the error I receive:**
standard_init_linux.go:190: exec user process caused "no such file or directory"

**Could this have to do with hidden line feeds?**

I'm building the Docker image on a Windows 10 machine.  

If I run with the entrypoint.sh that is building in the pre-built image microgateway that is pulled down from the google registry I don't receive this issue.

**Here is how I'm building the image:**

docker build --build-arg ORG="{my-org}" --build-arg ENV="test" --build-arg KEY="{my-key}" --b
uild-arg SECRET="{my-secret}" -t microgateway:sample2 .

The Image builds successfully (albeit I receive the following warning from docker One or more build-args [KEY ORG SECRET ENV] were not consumed)

**Here is how I'm running the image:**

docker run -P -p 8000:8000 --name microgateway -e EDGEMICRO_DOCKER=1 -e EDGEMICRO_ORG={my-org} -e EDGEMICRO_ENV=test -e EDGEMICRO_KEY={my-key} -e EDGEMICRO_SECRET={my-secret} -e SERVICE_NAME=edgemicro microgateway:sample2

**Comment by srinandan** [comment]
@chrislangston - We have made several changes to entrypoint.sh and Dockerfile. 

The issue with "no such file or directory" is most likely because the user doesn't have permission or bash is not available. We no longer include bash in the container. Please try this one more time with the changes and see if you still see the problem.
