### ISSUE TITLE
Retrieve new proxy endpoint and target endpoint from microgateway

### ISSUE THREAD

**Issue by satish1240** [apigee-internal/microgateway#272]
Currently microgateway only retrieves default proxy and target endpoints info from apigee edge api proxy

Lets say in same edge api proxy if we add one more route by creating another basepath in another proxy endpoint and routing to another target endpoint files, microgateway is not retrieving those.

How to retrieve additional routes with new basepaths, proxy and target endpoints from the same apiproxy

@keyurkarnik @srinandan @anil614sagar

**Comment by srinandan** [comment]
That's not possible OOTB. Please take a look at: https://github.com/srinandan/router or https://github.com/srinandan/bprouter
