### ISSUE TITLE
Memory leak starting with version 3.1.0

### ISSUE THREAD

**Issue by fpavageau** [apigee-internal/microgateway#282]
A memory leak is present in microgateway-plugins starting with version 3.0.12 (see apigee/microgateway-plugins#174), which impacts this application from 3.1.0 if you use one on the impacted plugins (`apikeys`, `oauth`, `oauthv2`), making it unsuitable for production use.

Once the plugins are fixed and released, the dependency should be updated here.

**Comment by keyurkarnik** [comment]
Fixed in tag 3.1.3
