### ISSUE TITLE
Bad release for 3.1.3

### ISSUE THREAD

**Issue by fpavageau** [apigee-internal/microgateway#284]
3.1.3 seems to be uninstallable: running `npm install -g edgemicro@3.1.3` results in lots of messages similar to
```
 npm WARN tar ENOENT: no such file or directory, open '/usr/local/lib/node_modules/.staging/rxjs-52ef0c20/operator/skip.js'
 npm WARN tar ENOENT: no such file or directory, open '/usr/local/lib/node_modules/.staging/rxjs-52ef0c20/operators/skip.js'
 npm WARN tar ENOENT: no such file or directory, open '/usr/local/lib/node_modules/.staging/rxjs-52ef0c20/add/operator/skipLast.js'
 npm WARN tar ENOENT: no such file or directory, open '/usr/local/lib/node_modules/.staging/rxjs-52ef0c20/internal/operators/skipLast.js'
 npm WARN tar ENOENT: no such file or directory, open '/usr/local/lib/node_modules/.staging/rxjs-6f24048c/internal/util/errorObject.js'
…
```

**Comment by edwinyoung** [comment]
Adding error message to this:

```
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/apigee/microgateway-config.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

**Comment by edwinyoung** [comment]
Want to add that running `git ls-remote -h -t ssh://git@github.com/apigee/microgateway-config.git` on my local machine works just fine, but `npm` seems to be failing on this command for a reason I can't determine.

**Comment by nairpraving** [comment]
Agree,
I am seeing the same issue, also migrating to buster from alpine, so this
email helped.

else I would have gone into a rabbit hole.

**Comment by atoom** [comment]
Same issue for us!

I have opened a ticket with Apigee support - hopefully they will get someone from the development team to look at this.

**Comment by keyurkarnik** [comment]
Installing git on the target machine solves the issue. That is not a fix, but a workaround

**Comment by keyurkarnik** [comment]
Deprecated version 3.1.3.
Replaced with version 3.1.4

This issue was caused by core pulling in an incorrect dependency. The issue gets manifested only when git is not available on the target machine.
