### ISSUE TITLE
Apigee Edge Micro Gateway - Configure Error - Script node is still starting

### ISSUE THREAD

**Issue by anil614sagar** [apigee-internal/microgateway#60]
Using Apigee Edge Microgateway Version 2.1.2, Trying to configure Apigee Edge settings. Below error is seen. Had anyone seen similar issue ? Any idea what's happening behind the scenes ? Any information regarding same will be helpful.

$> edgemicro configure -o xxxx -e test -u xxx@xxx.com 

{ [Error: cannot GET https://XXXX-test.apigee.net/edgemicro-auth/publicKey (500)]

  text: '{"fault":{"faultstring":"Script node is still starting","detail":{"errorcode":"scripts.node.runtime.ScriptStillStarting"}}}' }

PS: Running same command once again solved the issue, Interested to know what exactly hapenning behind scenes.

We need to better handle this error [maybe a retry]

**Comment by srinandan** [comment]
@anil614sagar - Looks like the edgemicro-auth proxy did not deploy properly on Edge. The edgemicro-auth proxy is a node.js proxy (a127). I can't tell why now, but that proxy failed to start. Looks like it worked the second time around.

We are working on a new implementation of this proxy that does not use node.js. This error shouldn't happen in the future.
