### ISSUE TITLE
Performance problems & MG restarts during streaming.

### ISSUE THREAD

**Issue by rajeevapigee** [apigee-internal/microgateway#65]
I see performance degradation when doing streaming through microgateway. The testing was done using [artillery](https://artillery.io/docs/gettingstarted.html) and using files ranging from size 100kiB to 100miB. The results are a comparison between apache and MG. On the logs I can also multiple restarts on MG.

To replicate the testing please see [here](https://github.com/orionhealth/apigee-edgemicro-testing)

<img width="553" alt="screen shot 2016-10-28 at 2 33 17 pm" src="https://cloud.githubusercontent.com/assets/1038424/19794130/8290c8d8-9d1b-11e6-980c-03df4ffc2752.png">
## Results -

see explanation [here](https://artillery.io/docs/gettingstarted.html#reading-the-output) 
```====== EDGE MICRO ======== 

all scenarios completed
Complete report @ 2016-10-26T19:52:24.016Z
  Scenarios launched: 75
  Scenarios completed: 33
  Number of requests made: 853
  RPS: 2.22
  Request latency:
    min: 1.5
    max: 15649.9
    median: 21.6
    p95: 10018.8
    p99: 10304.8
  Scenario duration:
    min: 50935.2
    max: 116087.1
    median: 75387.9
    p95: 109780.1
    p99: NaN
  Codes:
    200: 687
    502: 123
    503: 43
  Errors:
    ECONNRESET: 42

=========  APACHE ======
all scenarios completed
Complete report @ 2016-10-26T20:00:08.362Z
  Scenarios launched: 75
  Scenarios completed: 67
  Number of requests made: 1160
  RPS: 3.45
  Request latency:
    min: 0.6
    max: 625.7
    median: 1.5
    p95: 90.8
    p99: 324.6
  Scenario duration:
    min: 41772
    max: 43868.8
    median: 42702.7
    p95: 43649.7
    p99: 43846.2
  Codes:
    200: 1160
  Errors:
    ECONNRESET: 8```

**Comment by F1ERRO** [comment]
working on this now

**Comment by f1erro** [comment]
https://github.com/apigee/microgateway-core/pull/39 fixes this
