### ISSUE TITLE
edgemicro configure fails when run multiple times

### ISSUE THREAD

**Issue by dibyom** [apigee-internal/microgateway#68]
Running `edgemicro configure` multiple times leads to the following error:
```
creating vault
{ [Error: cannot POST https://api.e2e.apigee.net/v1/organizations/radical-new/environments/prod/keyvaluemaps (409)]
  text:
   { code: 'keyvaluemap.service.keyvaluemap_already_exist',
     message: 'KeyValueMap microgateway already exists',
     contexts: [] } }
```

The configure command should continue with the rest of the configuration if the KVM already exists so users can retry the command in case it fails midway

**Comment by F1ERRO** [comment]
commit introducing this bug reverted
