### ISSUE TITLE
PrivateKey stored in clear text

### ISSUE THREAD

**Issue by dibyom** [apigee-internal/microgateway#71]
The privateKey is stored in cleartext KVM. We should use encrypted KVM whenever possible.

**Comment by srinandan** [comment]
We are not going add this change (KVM) in the current release (2.3.0). We will continue to use vault until Encrypted KVM becomes available to OPDK customers also.

@mdobson - FYI ^

**Comment by srinandan** [comment]
privateKey in encrypted KVM. This can be closed.
