### ISSUE TITLE
Configure for Apigee Private Cloud does not include the newly added configDir option.

### ISSUE THREAD

**Issue by dmryn** [apigee-internal/microgateway#98]
I noticed that a new option -c or --configDir #86 was added to the 2.3.3 beta which is something we where looking for but it's missing for the Private Cloud configure.  Are there plans to add this to the private configure?

 ./node_modules/edgemicro/cli/**edgemicro private configure**
current nodejs version is v7.5.0
current edgemicro version is 2.3.3-beta
username is required

  Usage: configure [options]
  Automated, one-time setup of edgemicro with Apigee Private Cloud
  Options:

    -h, --help                          output usage information
    -o, --org <org>                     the organization
    -r, --runtime-url <runtimeUrl>      the URL of the runtime server
    -m, --mgmt-url <mgmtUrl>            the URL of the management server
    -e, --env <env>                     the environment
    -u, --username <user>               username of the organization admin
    -p, --password <password>           password of the organization admin
    -v, --virtual-hosts <virtualHosts>  comma separated virtual hosts to deploy with

**Comment by mdobson** [comment]
Hi Dave,

Apologies on this oversight. This should also be included with the `private configure` command as well. Thanks for filing the issue!

-Matt

**Comment by dmryn** [comment]
Thanks. Do you know if this will make it in the 2.3.3 release? This will be critical to us being able to use our CI/CD pipeline for deploying to CF. Also looking to 2.3.3 release since 2.3.1 logging is broken as well.

**Comment by mdobson** [comment]
Unfortunately the 2.3.3 release actually just dropped this morning. (Just unannounced yet.)

Logging will be fixed in 2.3.3, but this will not. 

Apologies,

-Matt
